[workspace]
members = [
    "trading-common",
    "trading-api",
    "trading-bot"
]
resolver = "2"
[workspace.dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tokio-tungstenite = { version = "0.24.0", features = ["native-tls"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
chrono = { version = "0.4.38", features = ["serde"] }
postgrest = "1.6.0"
axum = "0.7.7"
dotenv = "0.15.0"
anyhow = "1.0.89"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
thiserror = "1.0.64"
cargo-watch = "8.5.3"
base58 = "0.2.0"
base64 = "0.22.1"
arrayref = "0.3.9"
futures-util = "0.3.31"
solana-sdk = "2.0.13"
solana-client = "2.0.13"
solana-account-decoder = "2.0.14"
solana-program = "2.1.0"
spl-token = "7.0.0"
surf = "2.3.2"
once_cell = "1.20.2"
spl-associated-token-account = "6.0.0"
arc-swap = "1.7.1"
solana-transaction-status = "2.0.14"
borsh = "1.5.1"
bs58 = "0.5.1"
parking_lot = "0.12.3"