services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
  wallet:
    build:
      context: .
      dockerfile: trading-wallet/Dockerfile
    environment:
      - RUST_LOG=info
      - WALLET_SERVICE_ADDR=0.0.0.0:50051
    ports:
      - "50051:50051"
  api:
    depends_on:
      - wallet
      - redis

  bot:
    depends_on:
      - wallet
      - redis
volumes:
  redis_data:
